dev-dependencies = { }

[dependencies]
base = "0.11.1"
stableheapbtreemap = "1.5.0"
star = "0.1.1"
map = "9.0.1"
vector = "0.3.1"
ovs-fixed = "0.1.2"
candy = "0.3.0"
class-plus = "0.0.1"

[package]
name = "icrc72-publisher-mo"
version = "0.0.1"
description = "manage publications for icrc72"
repository = "https://github.com/PanIndustrial-Org/icrc72-publisher-mo"
keywords = [ "pubsub" ]
